### ISSUE TITLE
Make Stud::Task and Stud.interval more easy to interrupt

### ISSUE THREAD

**Issue by purbon** [jordansissel/ruby-stud#23]
Hi,
  the way ```Stud.interval``` works this days when handle interruptions is not suited for situation where the for example the code gets sleeping and need to be waken up, this is like this because the interruptions are handled by setting a flag.

```Stud::Task``` and his counterpart ```Stud.interval``` should be made more aware of interruptions so we are able to write something like:

```
 task = Stud::Task.new(*args) do |args|
     Stud.interval(time) do
        do stuff 
    end
 end

task.interrupt  # to stop the code
task.sleeping?  # to sleep the task
task.wakeup     # wakeup from sleep 
```

or 

```
  interval = Stud.interval(time) do
        do stuff 
    end

  interval.interrupt # to interrupt the interval
```

This would help out situation where the sleep should be for example interrupted or situation where the task being in place for the interval got stuck.

**Comment by purbon** [comment]
Related with: https://github.com/elastic/logstash/pull/3895

**Comment by colinsurprenant** [comment]
PR for this #27

**Comment by jordansissel** [comment]
Done in https://github.com/jordansissel/ruby-stud/pull/27
