### ISSUE TITLE
Task interruption state handing is broken

### ISSUE THREAD

**Issue by colinsurprenant** [jordansissel/ruby-stud#25]
while looking at #24 I noticed that `Thread.current` is being used in https://github.com/jordansissel/ruby-stud/blob/97f9ac41b754d8b4a2469c3a08ce86702e5fee40/lib/stud/task.rb#L32-L38  

I don't understand how this can work since Thread.current is the caller thread. Shouldn't it be `@thread[:stud_task_interrupted]` ??

**Comment by colinsurprenant** [comment]
copied from ny comment in https://github.com/jordansissel/ruby-stud/pull/24/files#r39216711

> haven't analyzed why a Task class @stud_task_interrupted ivar would not work here... but looking quickly at implementation, a Task object can only hold a single thread at a time and executes only once so I don't think we need a threadlocal here...

**Comment by jordansissel** [comment]
> I don't understand how this can work

This is my life in computers.

**Comment by jordansissel** [comment]
I agree it looks .... not right.

I confess I wrote Stud::Task but I don't think I use it many places. Where I remember using it, I use it for capturing thread exits, not necessarily for interruption. (aka Stud::Task#wait is what I cared most about, less about stop)

+1 on fixing it so Stud::Task can be requested to stop and having some correct implementation of it :)

**Comment by jordansissel** [comment]
> @thread[:stud_task_interrupted] ??

I agree. probably should be replaced with an atomic boolean instead of an ivar hash value

**Comment by colinsurprenant** [comment]
PR for this #27

**Comment by jordansissel** [comment]
Done in https://github.com/jordansissel/ruby-stud/pull/27
