### ISSUE TITLE
interval interruption handling is broken

### ISSUE THREAD

**Issue by colinsurprenant** [jordansissel/ruby-stud#26]
relates to #25 

 `Stud#interval` relies on the `Task` interruption state handling to verify for interruption, see https://github.com/jordansissel/ruby-stud/blob/97f9ac41b754d8b4a2469c3a08ce86702e5fee40/lib/stud/interval.rb#L12
but a `Stud#interval` is not related to a `Task`, the actual task passed to `interval` is a block and this block is never made into a `Task` into `interval`, it is simply called. So I do not understand why `Task.interrupted?` is used here!?

From history this is a change committed by @ph.

**Comment by colinsurprenant** [comment]
PR for this #27

**Comment by jordansissel** [comment]
https://github.com/jordansissel/ruby-stud/pull/27
